### PR TITLE
fixed a few typos

### PR DESCRIPTION
**Pull request by Ashafix**
Encountered the function 'is_anacoda` while looking at issue #205, renamed it and fixed a few more typos.

### CODE REVIEW

**Comment by peternowee** [comment]
Reviewed. Looks good to me. Found no other occurrences of the renamed function, and the other two corrections are in comments. All tests pass (when run together with pydot/pydot#211).

**Comment by peternowee** [comment]
@Ashafix I rebased and merged your commit as a7639607c2a050b856bce70a6336feb637ab615e. It will be part of the next release, probably 1.4.2. Thanks!

**Comment by peternowee** [comment]
@Ashafix I notice that GitHub does not recognize your PR as having been merged. I rebased and merged locally, then pushed to GitHub. I was not sure what it would do. Next time I better try to give you some time to rebase it yourself if you want, although that is difficult if there are multiple PRs waiting to be merged. Or maybe next time I should use the GitHub interface instead of work locally, although that brings limitations with regard to signing. Related discussions in https://github.com/isaacs/github/issues/2, https://github.com/isaacs/github/issues/88 and https://github.com/isaacs/github/issues/361.

Anyway, I wonder what would happen if you would force-push the new commit a763960 over your branch Ashafix:master: If GitHub would then suddenly consider this PR to have been merged. I will reopen this PR for a few days in case you also want to try that out.

**Comment by peternowee** [comment]
@Ashafix On second thought, overwriting your branch with the new commit probably will not work either, because then your branch will just be equal to `pydot:master`, which will also close it automatically. I think we just have to forget about the final status of this PR according to GitHub. Sorry, hope you do not mind too much and I will see what I can do better next time. At least the commit log correctly shows your work was merged and that you were the Author; I hope you agree that is the most important. Again, thank you for your contribution and I will contact you about the PEP8 cleanup in the discussion below https://github.com/Ashafix/pydot/commit/38da0deccc645a89643238e40abb9b4983d26e85 later.

**Comment by Ashafix** [comment]
@peternowee : thanks for taking care of it!

I saw that two unittests are failing.
Should I be looking into that or is something unrelated to the PR?

**Comment by peternowee** [comment]
@Ashafix You mean the failing AppVeyor ones, right? See pydot/pydot#213 for that. Help is welcome, as I don't have Windows myself, so I cannot even start to try to reproduce it locally. With some effort, it is possible to access the AppVeyor VM's, but only for a limited time after each run. It seems to be a very AppVeyor-specific problem, since I did not see any reports of this problem yet, so it may be difficult/impossible to reproduce on a local Windows-installation. Maybe AppVeyor support needs to be contacted. Anyway, for now I just ignore the AppVeyor failures on those specific tests.

**Comment by peternowee** [comment]
> @peternowee : thanks for taking care of it!
> 
> I saw that two unittests are failing.
> Should I be looking into that or is something unrelated to the PR?

**Comment by peternowee** [comment]
And just to answer your question more clearly: No, these two failing tests at AppVeyor are not related to this PR, but of course any help is welcome on solving them. Again, see pydot/pydot#213.

**Pull request closed without merging**
