### PR TITLE
Move errno from os to builtin. Fixes #177

### LINKED ISSUE #177: os.errno will be removed in python3.7
pydot uses os.errno here:

https://github.com/erocarrera/pydot/blob/master/pydot.py#L1863

See https://bugs.python.org/issue33666

### PR DESCRIPTION
**Pull request by dchimeno**
Fixes #177

### CODE REVIEW

**Comment by leycec** [comment]
**This is a critical pull request.**

PyDot and hence all downstream projects (e.g., [our multiphysics biology simulator](https://gitlab.com/betse/betse), which leverages PyDot to graph non-trivial gene regulatory networks (GRNs)) are currently incompatible with Python >= 3.7. This is a hard blocker for us and presumably others.

## How Now Shall We Proceed?

Would expediting this merger and rapidly publishing a new stable release be feasible, @johnyf? The last stable release was nine months ago, which... is a bit disconcerting. You've done a phenomenal job thus far, but it's hard not to feel that the project has begun to [bit rot](https://en.wikipedia.org/wiki/Software_rot).

That's bad. PyDot re-entering a moribund, shambling, zombie-like state of half death invites *yet another* resurgence in PyDot forks, splitting the Python-based GraphViz community *yet again.*

Let's avoid that at all cost, please.

## Towards a Bold New Future

If you no longer have adequate time to maintain PyDot, that's perfectly understandable. Only the most battle-hardened open-source advocates can wearily trudge forward for decades with no financial incentive. You're on a purely volunteer basis here, after all.

Would bringing one or more proven developers onto the project be of any assistance? For example, does @prmtl already have commit access? I note that he's both a member of the [pydot group](https://github.com/pydot) *and* has [successfully contributed four prior pull requests to this project](https://github.com/erocarrera/pydot/pulls?q=is%3Apr+is%3Aclosed). A prime candidate emerges!

And... no, I'm not volunteering for the position. [Yakuza 0](http://www.metacritic.com/game/pc/yakuza-0) won't play itself, after all. :video_game: 

In any case, thanks for the long years of tireless effort, @johnyf. I still believe in you.

**Comment by prmtl** [comment]
About commit access - unfortunately I do not have any. It would be nice if actually there would more than one person with access to both the repo and pypi package, but it's up to @johnyf who (if any) will have it. As always, I volunteer to give back [pydot](https://github.com/pydot) organisation to have nice urls ;).

And about a future: since I'm not using pydot for a long time (and this is why I'm not make any more commits), it would be hard for me to add new features, but I would be able to review and merge simpler PRs.

**Comment by leycec** [comment]
Let's give this pull request until September 1st. If there's still no word from @erocarrera and/or @johnyf by then, perhaps we can consider... *options.* By which I mean a fork, Gods help us all.

**Comment by ErikBoesen** [comment]
[`pydot-ng`](https://github.com/pydot/pydot-ng) works for me. Perhaps refocus development efforts there?

**Comment by leycec** [comment]
@ErikBoesen: Excellent catch; I hadn't realized that [pydot/pydot-ng](https://github.com/pydot/pydot-ng) was still vigorously maintained. That said, abandoning [erocarrera/pydot](https://github.com/erocarrera/pydot) introduces non-trivial issues for downstream consumers – notably:

* [NetworkX](https://github.com/networkx/networkx/blob/bf1c7cc9b144767523e5abcf84f949d4223848a0/networkx/drawing/nx_pydot.py), which [**hardcodes** usage of `pydot`](https://github.com/networkx/networkx/blob/bf1c7cc9b144767523e5abcf84f949d4223848a0/networkx/drawing/nx_pydot.py). Sadly, I authored the pull request transitioning NetworkX from the unmaintained `pydotplus` project to the then-maintained `pydot` project. Rather than submitting *yet another* NetworkX pull request transitioning from `pydot` to `pydot-ng`, it might be useful to investigate whether or not the [`networkx.drawing.nx_pydot`](https://github.com/networkx/networkx/blob/bf1c7cc9b144767523e5abcf84f949d4223848a0/networkx/drawing/nx_pydot.py) project could be trivially monkey-patched at runtime by client applications to switch from `pydot` to `pydot-ng`. It *probably* can be, because all things can be monkey-patched if you hammer away at them diligently enough. If NetworkX can be monkey-patched to support `pydot-ng`, that would temporarily satisfy our needs... maybe. Monkey-patches are invariably fragile. Official support would certainly be preferable. `</sigh>`
* The [`pydot` conda-forge feedstock](https://github.com/conda-forge/pydot-feedstock) contains *significant* portability improvements that would need to be merged into the `pydot-ng` conda-forge feedstock. Specifically, Anaconda's GraphViz is fundamentally broken on Windows – requiring that *all* Graphviz-based Anaconda packages manually patch their upstream codebases to hack around the brokenness. Again, I authored the pull request resolving this issue in the [`pydot` conda-forge feedstock](https://github.com/conda-forge/pydot-feedstock). Since there currently exists no corresponding `pydot-ng` conda-forge feedstock, `pydot-ng` will remain unusable under Windows when installed via Anaconda. **This is bad.**

In short, there are [roadblocks to peace](https://www.youtube.com/watch?reload=9&v=p-2TxIcdaOs). All of the above speedbumps are, of course, trivial in the technological sense but non-trivial in the bureaucratic sense. Pull requests consume scarce volunteer resources – namely, mine. <sup>*This is also bad.*</sup>

## Arise, pydot-ng! Arise!

@prmtl: This is your time to shine! Before we make the permanent plunge into the healing waters of `pydot-ng`, however, I have a few lingering concerns:

* How committed are you to maintaining `pydot-ng` in perpetuity? While I see that [you've recently reignited development after a two-year (**!**) hiatus](https://github.com/pydot/pydot-ng/commits/master), <sup>*which is awesome, by the way*</sup> I'm concerned that development will inevitably stagnate when [erocarrera/pydot](https://github.com/erocarrera/pydot) eventually reawakens from its deep slumber.
* Would porting the most critical bug fixes and newly introduced features from this repository into `pydot-ng` be feasible? Until recently, this repository is where all tha sweet `pydot` action happened. Now that that's no longer the case, it would be a brutal loss if the past several years of `pydot` improvements were to be summarily discarded by `pydot-ng`. Perhaps someone could try interactively rebasing `pydot-ng` back onto the current HEAD of the `dev` branch of `pydot`?
* Would adding one or more committed developers to `pydot-ng` be feasible? If I wasn't *swamped* with work elsewhere, I'd happily suggest myself. Since I am, I won't. Would anyone else participating in this thread happen to be sacrificially interested?

Thanks again for the recent resuscitation of `pydot-ng`, @prmtl. May you avoid the `pydot` curse and continue to ~~slave~~ volunteer away at `pydot-ng` long into your dotage. *Two cheers for the next generation!*

**Comment by prmtl** [comment]
@leycec I would love to add some other maintainers, even just in case that it will happened what seems to be the curse of maintaining `pydot` - disappearing maintainers ;) There is one person that was working on `pydot-ng` together with me, so there always be someone to ask for access. But sadly, there are no serious candidates for maintainers (well... actually even no contributors ;)).
As you noticed and wrote, I've revived the repo to make it testable od linux and windows and slowly introducing changes and fixes. Of course I'll do my best, but again: contributions welcome.

**Comment by prmtl** [comment]
Handled in #191

**Pull request closed without merging**
