### PR TITLE
propagate 'SYSTEMROOT' when calling GraphViz

### PR DESCRIPTION
**Pull request by hoverjmt**
This commit fixed the error described in issue #203 Problem with graph.write.png...AssertionError: 1.

The dot command in Windows was missing the extra SYSTEMROOT environment variable.

### CODE REVIEW

**Comment by ikiddoi** [comment]
how tf does someone propagate systemroot lul

**Comment by ikiddoi** [comment]
any update omegalul

**Comment by peternowee** [comment]
@hoverjmt Congratulations on your first PR! At the same time, sorry to see your PR did not get any response yet. I am also just a user here to share back my own improvements and as it seems the maintainer is already quite busy (no problem, of course, that's how it goes), I thought I would have a look around and see if I could help expedite some of the other issues and PRs waiting in the queue. As such, I am not able to do much for you except give my comments.

As I mentioned in issue pydot/pydot#203, the `AssertionError: 1` from `create` is by itself not enough reason to assume that you solve the same problem that the OP of that issue had. Judging by your comment above that your PR solves a Windows-specific issue and by the DOT string-related error messages reported by the other two reporters there, I suspect that the underlying issue that you solve here was actually very different from theirs. That is not to say your change is not needed, of course! Who knows how many people are wasting their time right now finding their own solution to the problem you already solved here.

If you still have the exact GraphViz error that you got (shown above or below the traceback), perhaps you could add that as a comment here, so it may be easier to find for others. Also, consider providing some more explanation in the commit message, for example: "Currently, under these conditions: ......, this error can occur: ....., because ......... This commit prevents that error by .........". Optionally, if you tested your change and if you considered possible side-effects or risk of regressions, you can mention that there as well, although that may be a bit too much for this small change. Anyway, a bit more background information to make it easier for future contributors to understand the code change. For this, I prefer commit messages over comments in a PR, because I have seen codebases get disconnected from, or even completely loose, their issue and PR history during forks and project migrations. To change your commit message, unless the maintainer tells you otherwise, I think you can still just `git commit --amend` it and then force-push your branch over the current one.

Other than that, because I do not use Windows, I cannot really say much about the actual change you propose. Hopefully, it will get reviewed soon.

Hope this helps, all the best!

**Comment by peternowee** [comment]
Maybe this PR pydot/pydot#208 was a solution to issue pydot/pydot#205. Before confirming that, please check carefully that the error `AssertionError: 1` was caused by `dot.bat`/`dot.exe` extension problems, because that error code has many other possible causes as well.

**Comment by peternowee** [comment]
@hoverjmt I have recently been granted commit rights to this repository, so I plan to merge some of the open PRs soon. I still don't know what to do with your PR. Do you think you will have the opportunity to answer my questions of September 2019 anytime soon, or have you moved on to work on other things? Please reply within a few days, even if you need more time than that, so that I can at least start planning.

To anyone else who found this PR to solve their problem: Please add a comment to confirm that and if you can, please add some more details about the problem it solves or the workings of the solution.

**Comment by peternowee** [comment]
@shakedbr It seems that PR is exactly what you are suggesting in pydot/pydot#244, right? Except for the `is_windows()` conditional, but I think we can do without that, right? If `SYSTEMROOT` does not exist, it will fall back to an empty string anyway and if `SYSTEMROOT` does exist, I do not see how passing it could do any damage on a non-Windows platform, because as far as I know, Graphviz itself does not look at it.

Happy to finally see some confirmation come in for this PR, thanks!

**Comment by shakedbr** [comment]
@peternowee Yes, this PR solves the problem I encountered in #244 . 
The condition is, indeed, not necessary.

I was glad to help!

**Comment by peternowee** [comment]
@shakedbr Perhaps you can also provide the exact error message that this solves. I am quite curious about that.

**Comment by shakedbr** [comment]
The error message isn't that informative
```
....
File "C:\Users\shakedbr\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\pydot.py", line 1723, in new_method
    format=f, prog=prog, encoding=encoding)
  File "C:\Users\shakedbr\AppData\Local\Continuum\anaconda3\envs\py36\lib\site-packages\pydot.py", line 1945, in create
    assert process.returncode == 0, process.returncode
AssertionError: 1
```

**Comment by peternowee** [comment]
@shakedbr Sorry, few more questions, if you have time:
- Was there nothing above that traceback, starting with `stdout, stderr:`? Sometimes the `stderr` output has something like `... is not recognized as an internal or external command, operable program or batch file`.
- I see you use anaconda. Did you install Graphviz from the conda/Anaconda package in the anaconda environment, or directly in Windows (using the Windows intaller from the Graphviz.org for example)?
- Did you use pydot 1.4.1 or git master (1.4.2.dev0)?

I am curious if this is related to the `.bat`/`.exe` issues we have been seeing earlier (pydot/pydot#205). We recently merged another partial fix for that in master.

Thanks.

**Comment by shakedbr** [comment]
* I get this message before the traceback:
```
"dot" with args ['-Tdot', 'C:\\Users\\shakedbr\\AppData\\Local\\Temp\\tmpx7btobvz'] returned code: 1
stdout, stderr:
 b''
b''
```
* I installed Dot with conda (it tries to call to `.bat` file)
* pydot 1.4.1

I don't think it's related to #205 . It's purely `Popen` issue.

**Comment by peternowee** [comment]
Ok, clear, thank you! I will merge this PR now then. Thanks a lot!

**Comment by peternowee** [comment]
Ran CI test suites from my own accounts with this PR rebased on master:
- Travis CI: All passed.
  https://travis-ci.com/github/peternowee/pydot/builds/200371207
- AppVeyor: Except the known failing AppVeyor tests (see pydot/pydot#213), all other tests pass.
  https://ci.appveyor.com/project/PeterNowee/pydot/builds/36272653

**Comment by peternowee** [comment]
@hoverjmt In case you are still watching this issue, I just merged your PR through the GitHub web interface. Unfortunately, GitHub changed your email address in the git commit Author field in the process to your github.com user address (see https://github.com/isaacs/github/issues/1368). Sorry about that, this is also a bit new to me. If I had merged it myself locally and then pushed to GitHub, GitHub would not have considered this PR as "merged". It seems there is no good solution for that. Anyway, thanks a lot for your contribution, hope to see you again!

**Pull request merged**
