### PR TITLE
Tests: Add coverage, use pytest as test runner

### PR DESCRIPTION
**Pull request by ferdnyc**
As promised, this is a WIP set of changes to add code coverage collection and reporting to our CI testing, switching from unittest-parallel to pytest (with pytest-xdist and pytest-cov plugins) as the test runner.

As it turns out, happily we **don't** have to convert the base test code away from unittest in order to reap the benefits of pytest's parallelism and code-coverage integrations. I still think we SHOULD, but for the moment testing with pytest running the unittest-based tests seems to work fine.

The PR currently contains the necessary `setup.cfg` changes to integrate pytest and coverage-collection, along with a `.coveragerc` to configure the process and GitHub Actions workflow changes to collect and aggregate the coverage data.

It's that last step that fails, because the coverage data from the various runners appears to embed full paths to the module being tested. In the separate coverage job (which runs after all of the testing, always on Ubuntu using the system python) those installed paths no longer exist. (And can't be recreated because they embed paths specific to the tox environment in use at the time.) So `coverage report` immediately bails with an error like this:

> No source for code: '/Users/runner/work/pydot/pydot/.tox/py310/lib/python3.10/site-packages/pydot/__init__.py'.
> Error: Process completed with exit code 1.

So, the first step is figuring out how that's all supposed to be made to work, I assume it's just a `.coveragerc` setting that needs to be tweaked, or something.

Then we need to figure out how to get the coverage data _reported_ usefully. (`coverage report` just produces a summary like this, which isn't immediately helpful for evaluating PR changes and the like:)
```text
Name                                                          Stmts   Miss Branch BrPart  Cover
  -----------------------------------------------------------------------------------------------
  .tox/py312/lib/python3.12/site-packages/pydot/__init__.py         9      0      0      0   100%
  .tox/py312/lib/python3.12/site-packages/pydot/core.py           687    124    298     34    79%
  .tox/py312/lib/python3.12/site-packages/pydot/dot_parser.py     273     44    134     23    80%
  .tox/py312/lib/python3.12/site-packages/pydot/exceptions.py       6      2      0      0    67%
  test/__init__.py                                                  0      0      0      0   100%
  test/test_pydot.py                                              386     28     52      8    90%
  -----------------------------------------------------------------------------------------------
  TOTAL                                                          1361    198    484     65    82%
```

(Our overall coverage numbers are actually better than I'd expected, which is good news.)

And we need to decide about converting the test suite itself from unittest to pytest, which I still think is a good idea and worth doing, but appears to be less urgent than it initially appeared.

### TODO

- [ ] Fix paths in coverage data so that `coverage combine` isn't looking for runner-specific paths
- [ ] Set up some sort of coverage annotation/reporting driven by the collected data
- [ ] Migrate tests from unittest to pytest?

### Effects on CI runs

Not particularly surprisingly, adding coverage collection has almost no effect on the Ubuntu or macOS runners. (In fact, the execution time difference falls within the general randomness of job execution times for GitHub Actions overall — could be a bit slower, could be a bit faster.) On Windows, it adds maybe 40-60 seconds (40%) to the execution time for each runner. So, not unreasonably slow by any means.

(A recent run on `main`, vs. a run on this branch)

image image

### CODE REVIEW

**Comment by ferdnyc** [comment]
Aaand, guess who forgot to add license comments to the `.coveragerc`?

**Comment by ferdnyc** [comment]
Grr. I figured out how to fix the installed paths by adding `site-packages` to the coverage path roots, but now it's bailing with this:

> No source for code: '/Users/runner/work/pydot/pydot/src/pydot/__init__.py'.

...Because that's a macOS runner path, and the aggregation job is running on Ubuntu. Grrr.

**Comment by ferdnyc** [comment]
I really need to sort out this path bullcrap.

**Comment by ferdnyc** [comment]
Hey, that actually worked!

Drew-got-animated-during-her-acceptance-speech

Now, on to the next hurdle of actually _doing_ something with the aggregated data. (ISTR reading a blog post about some GitHub Actions annotation stuff that could be done with the data in a `coverage.xml` file... not sure if it was by coverage.py dev Ned Batchelder, or someone else.)

**Comment by ferdnyc** [comment]
So the comment that _would've_ been posted, had the secure workflow run (it's a new `.github/workflows/coverage.yml` file that doesn't exist in the main repo yet, so it won't run until merged) is:

<hr>

 

_This PR does not seem to contain any modification to coverable code._



<hr>

Which is admittedly not very exciting. But they have examples of the comment format in [their sample repo](https://github.com/py-cov-action/python-coverage-comment-action-v3-example), and they look like this for external PRs:

image

and like this for internal PRs (not from a fork):

image

...Why there would need to be any difference between the two, when the job split and secure second workflow should make it so it doesn't matter, I don't entirely understand.

But I have, and have asked, [several questions](https://github.com/py-cov-action/python-coverage-comment-action/issues/461) about the action's handling of security.

**Comment by ferdnyc** [comment]
The Python Coverage Comment devs [have answered my questions](https://github.com/py-cov-action/python-coverage-comment-action/issues/461#issuecomment-2308941313) more-than-satisfactorily; I'm confident that their recommended configuration is safe to use.

However, because the workflows only _remain_ safe if they're not modified in unsafe ways, one extra level of security I thought of was to set [`CODEOWNERS`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) mappings so that PRs messing with either of the coverage-involved workflows (`ci.yml` and `coverage.yml`) will automatically request review from Responsible Parties™.

I'm adding a `CODEOWNERS` file to this PR that will designate @lkk7 as a code owner for both files, for that reason. (I'm not generally in the habit of assigning duties to other people, but code owners have to be committers to the repo in question, since they're the only ones who can approve PRs for merge. So, I'm not eligible to be on that list myself. But if you'd like any other users added, let me know.)

**Comment by ferdnyc** [comment]
And with that last change, I'm fairly confident that this is ready to go. We won't be able to get a good feel for it until the workflows in question are merged to the `main` branch and start operating on PRs, but such is the nature of GitHub Actions.

**Comment by ferdnyc** [comment]
Aaaand, forgot the REUSE data for `CODEOWNERS`.

**Review by lkk7 — APPROVED** [review]
This doesn't affect `pydot` itself, so let's not waste time. Let's get it into `main` as soon as possible to catch any problems.

**Pull request merged**
