### PR TITLE
Fix multiple breaking issues from new `pyparsing` versions

### PR DESCRIPTION
**Pull request by lkk7**
This PR:
- Fixes broken whitespace behavior which caused almost every dot file to be parsed incorrectly (https://github.com/pydot/pydot/issues/291, https://github.com/pydot/pydot/issues/289, https://github.com/pydot/pydot/issues/280, https://github.com/pydot/pydot/issues/277)
- Fixes broken HTML parsing (found through tests `html_labels.dot`, `html2.dot`)
- Fixes broken parsing for identifiers with non-standard characters (found through test `russian.dot`)
- Removes a few unused imports/variables.
- Bumps the version of `pyparsing` to `>=3.0.9`

Tradeoff: from my tests, there is a small performance degradation due to introduction of `pyparsing_unicode.BasicMultilingualPlane.alphanums` which impacts `pyparsing`'s speed. This can be investigated later. For now, the most important thing is that it works.

### CODE REVIEW

**Comment by InfamyStudio** [comment]
Someone merge this in!

**Comment by lkk7** [comment]
@InfamyStudio I've done it so long ago that I don't remember what I did there 😄

I believe currently only @prmtl is capable of merging this

**Comment by lkk7** [comment]
@prmtl @peternowee  Could you check this PR? You're the only active people there.
There are issues coming in and nobody to answer them.
I'd be happy to take over and contribute – this package still has a ton of downloads and users.

**Comment by MridulS** [comment]
Just wanted to +1 this, we (networkx) are planning on deprecating support for https://github.com/networkx/networkx/issues/5723 for some time now as pydot doesn't seem to be maintained. It breaks certain part of our graphviz/drawing test suite, and a lot of pydot issues are reported to us by networkx users.

It would be great to get some activity here to bring pydot up to date with the latest python/pyparsing releases!! pydot is super useful in cases where users just want to generate .dot files and it's pure python (easily WASM'able).

**Comment by lkk7** [comment]
@MridulS I've managed to get access to the repo. I'll be able to relearn and review my old changes in this PR and possibly merge them – maybe this weekend. There's a huge test suite that will help.

Another thing is actually publishing them as a new version if they'd work – I probably don't have rights for that yet so I'll have to ask Ero for even more 🥲

**Comment by ferdnyc** [comment]
I see the current repo has CI definitions for AppVeyor and Travis; presumably Travis, at least, is a lost cause.

I'd be willing to work on a PR to migrate that into GitHub Actions, if you'd be interested in reviewing and merging that, @lkk7.

That'd then open the door to setting up automatic (or _non-_ automatic) PyPi publishing of releases as well, if the relevant credentials were stored in the repo's or org's secrets. Then anyone with the necessary rights to tag releases here could perform that step as well. Raise the bus factor a bit.

**Comment by ferdnyc** [comment]
(Actually I see #299 was already submitted to start that work. But then it was closed seemingly immediately after, with no explanation.)

**Comment by lkk7** [comment]
@ferdnyc Hi, thanks and feel free to replace the old workflows with GitHub Actions lint/test steps.

I'd suggest skipping the PyPI publishing part for now – Ero (the original owner) wants to publish the first few changes himself to gain confidence in us 😄
Then, if everything's OK, we'll be able to set that up for sure

**Comment by zen-xu** [comment]
How often will a new version be released?

**Comment by lkk7** [comment]
@zen-xu
Hi, I'm not sure.
I'm not the original maintainer so my priority now is just to release the fixing version to revive the project.

May I ask why are you asking? Any comments/feedback/help is welcome

**Pull request merged**
